import json
import os
from typing import Dict

from models import ItemInfo
from utils.constants import ItemType, Rarity, RARITY_SUFFIXES, EquipmentSlot


def _format_name(item_id: str) -> str:
    return item_id.replace("_", " ").title()


def _parse_rarity_from_id(item_id: str) -> tuple[Rarity, str]:
    lower_id = item_id.lower()
    for suffix, rarity in RARITY_SUFFIXES.items():
        if lower_id.endswith(suffix):
            base = item_id[: -len(suffix)]
            return rarity, base
    if lower_id.endswith("_fine"):
        return Rarity.FINE, item_id[:-5]
    return Rarity.NORMAL, item_id


class ItemRegistry:
    def __init__(self, base_path: str = "game_data/wiki_export/autogenerated"):
        self._items: Dict[str, ItemInfo] = {}
        self._recipes: list = []
        self._recipes_by_output: Dict[str, list] = {}
        self._base_path = base_path
        self._loaded = False

    def load(self):
        if self._loaded:
            return
        self._load_equipment()
        self._load_materials()
        self._load_collectibles()
        self._load_containers()
        self._load_consumables()
        self._load_recipes()
        self._loaded = True

    def _load_recipes(self):
        self._recipes = self._load_json("recipes.json")
        self._recipes_by_output = {}
        for recipe in self._recipes:
            output_id = recipe.get("output_item_id", "").lower()
            if output_id not in self._recipes_by_output:
                self._recipes_by_output[output_id] = []
            self._recipes_by_output[output_id].append(recipe)

    def get_recipes(self) -> list:
        self.load()
        return list(self._recipes)

    def get_recipes_for_item(self, item_id: str) -> list:
        self.load()
        return list(self._recipes_by_output.get(item_id.lower(), []))

    def _load_json(self, filename: str) -> list:
        path = os.path.join(self._base_path, filename)
        if not os.path.exists(path):
            return []
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    def _load_equipment(self):
        for item in self._load_json("equipment.json"):
            item_id = item.get("id", "")
            rarity_str = item.get("quality", "Normal")
            try:
                # Map equipment quality to our Rarity enum where applicable
                quality_to_rarity = {
                    "Common": Rarity.COMMON,
                    "Uncommon": Rarity.UNCOMMON,
                    "Rare": Rarity.RARE,
                    "Epic": Rarity.EPIC,
                    "Legendary": Rarity.LEGENDARY,
                    "Ethereal": Rarity.ETHEREAL,
                    "Normal": Rarity.NORMAL,
                    "None": Rarity.NORMAL,
                }
                rarity = quality_to_rarity.get(rarity_str, Rarity.NORMAL)
            except (ValueError, KeyError):
                rarity = Rarity.NORMAL

            slot = item.get("slot", "unknown")

            self._items[item_id.lower()] = ItemInfo(
                id=item_id,
                name=item.get("name", _format_name(item_id)),
                display_name=item.get("name", _format_name(item_id)),
                value=item.get("value", 0),
                item_type=ItemType.EQUIPMENT,
                rarity=rarity,
                keywords=tuple(item.get("keywords", [])),
                slot=slot,
            )

    def _load_materials(self):
        for item in self._load_json("materials.json"):
            item_id = item.get("id", "")
            rarity, _ = _parse_rarity_from_id(item_id)
            self._items[item_id.lower()] = ItemInfo(
                id=item_id,
                name=item.get("name", _format_name(item_id)),
                display_name=item.get("name", _format_name(item_id)),
                value=item.get("value", 0),
                item_type=ItemType.MATERIAL,
                rarity=rarity,
                keywords=tuple(item.get("keywords", [])),
            )

    def _load_collectibles(self):
        for item in self._load_json("collectibles.json"):
            item_id = item.get("id", "")
            self._items[item_id.lower()] = ItemInfo(
                id=item_id,
                name=item.get("name", _format_name(item_id)),
                display_name=item.get("name", _format_name(item_id)),
                value=item.get("value", 0),
                item_type=ItemType.COLLECTIBLE,
                rarity=Rarity.NORMAL,
                keywords=tuple(item.get("keywords", [])),
            )

    def _load_containers(self):
        for item in self._load_json("containers.json"):
            item_id = item.get("id", "")
            self._items[item_id.lower()] = ItemInfo(
                id=item_id,
                name=item.get("name", _format_name(item_id)),
                display_name=item.get("name", _format_name(item_id)),
                value=0,
                item_type=ItemType.CONTAINER,
                rarity=Rarity.NORMAL,
                keywords=(),
            )

    def _load_consumables(self):
        for item in self._load_json("consumables.json"):
            item_id = item.get("id", "")
            rarity, _ = _parse_rarity_from_id(item_id)
            self._items[item_id.lower()] = ItemInfo(
                id=item_id,
                name=item.get("name", _format_name(item_id)),
                display_name=item.get("name", _format_name(item_id)),
                value=item.get("value", 0),
                item_type=ItemType.CONSUMABLE,
                rarity=rarity,
                keywords=tuple(item.get("keywords", [])),
            )

    def get_item(self, item_id: str) -> ItemInfo:
        self.load()
        lower = item_id.lower()
        if lower in self._items:
            return self._items[lower]
        # Not in game data: infer from ID
        rarity, base_id = _parse_rarity_from_id(item_id)
        return ItemInfo(
            id=item_id,
            name=_format_name(item_id),
            display_name=_format_name(item_id),
            value=0,
            item_type=ItemType.UNKNOWN,
            rarity=rarity,
            keywords=(),
        )

    def get_value(self, item_id: str) -> int:
        return self.get_item(item_id).value

    def get_all_items(self) -> Dict[str, ItemInfo]:
        self.load()
        return dict(self._items)

    @property
    def item_count(self) -> int:
        self.load()
        return len(self._items)
